### PR TITLE
Attempt to unify makefile for different architectures

### PR DESCRIPTION
**Pull request by berianjames**
Sorry it took me so long to get to this!

Creating PR so we can discuss some code topics.

### CODE REVIEW

**Comment by berianjames** [comment]
This builds with make (and with fewer compiler warnings than before), but fails upon module import
```python
import magtense
from magtense.magstatics import Tiles

> ImportError: cannot import name 'magtensesource' from 'magtense.lib'
```

I think this is something in the f2py f90 file? I am trying to work it out

**Comment by berianjames** [comment]
It must be the subroutines wrappers in FortranToPythonIO.f90? Are they redirecting the module namespace a layer deeper?

**Comment by spollok** [comment]
I removed some unnecessary include paths for the gfortan compilation. I don't think it will resolve the issue, but as it worked previously with the additional Makefile, I wanted to make the compilation as similar as possible.

**Comment by berianjames** [comment]
Everything works now - it's ready to merge back into master!

**Comment by berianjames** [comment]
👍🏻 LGTM

**Review by spollok — APPROVED** [review]
Also tested on Windows and Linux. Can be merged now.

**Pull request merged**
